version: '3'

services:
  db:
    image: mariadb:10.6
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db

  php:
    build: .
    volumes:
      - ./:/var/www/html
      - /var/log/apache2/app:/var/log/apache2/
    ports:
      - 8080:80